# Dummy plugin file. Paper plugins are required.
name: SecondWind
version: 1.0-SNAPSHOT
main: com.hjk321.secondwind.deps.papertrail.RequiresPaperPlugins
description: Do not go gentle into that good night.
authors: [hjk321]
website: https://hangar.papermc.io/hjk321/SecondWind
api-version: '1.20.6'
